delete_customer:
    path: /customer/{id}
    controller: App\Controller\CustomerController::deleteCustomer
    methods: DELETE

patch_customer:
    path: /customer/{id}
    controller: App\Controller\CustomerController::patchCustomer
    methods: PATCH

post_create_customer:
    path: /customer
    controller: App\Controller\CustomerController::createCustomer
    methods: POST

get_all_customers:
    path: /customer
    controller: App\Controller\CustomerController::index
    methods: GET

get_customer:
    path: /customer/{id}
    controller: App\Controller\CustomerController::getCustomerById
    methods: GET

put_customer_update:
    path: /customer/{id}
    controller: App\Controller\CustomerController::updateCustomer
    methods: PUT
