post_create_customer:
    path: /customer/post
    controller: App\Controller\CustomerPostController::createCustomer
    methods: POST

get_all_customer:
    path: /customer
    controller: App\Controller\CustomerController::index
    methods: GET

get_customer:
    path: /customer/{id}
    controller: App\Controller\CustomerController::getCustomerById
    methods: GET

