version: "3"
services:
  php-fpm:
    build:
      context: ./dockerfile-phpfpm
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - '9000:9000'
    volumes:
      - ./symfony-app/symfony-app:/var/www/html
  nginx:
    container_name: nginx
    build:
      context: ./dockerfile-nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
    networks:
      - app-network
    depends_on:
      - php-fpm
  mysql:
    build:
      context: ./dockerfile-mysql
      dockerfile: Dockerfile
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Test1234
      - MYSQL_DATABASE=Training
      - MYSQL_USER=razvan
      - MYSQL_PASSWORD=1234
      - MYSQL_HOST=mysql
    ports:
      - '3306:3306'
    networks:
      - app-network
  rabbitmq:
    build:
      context: ./dockerfile-rabbitmq
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_DEFAULT_USER=razvan
      - RABBITMQ_DEFAULT_PASS=12345
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - app-network
  redis:
    build:
      context: ./dockerfile-redis
      dockerfile: Dockerfile
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
    networks:
      - app-network

volumes:
  db_data:
    driver: local
  cache:
    driver: local

networks:
  app-network:
    driver: bridge

