framework:
    messenger:
        failure_transport: failed

        transports:
            amqp:
                dsn: '%env(RABBITMQ_CONN)%'
            failed: 'doctrine://default?queue_name=failed'

        routing:
            'App\Message\RabbitMqMessage': amqp
